name: 'myntra_clv_bronze'
version: '1.0.0'
config-version: 2

profile: 'myntra_snowflake'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  myntra_clv_bronze:
    bronze:
      +materialized: view
      +schema: bronze_view