-------------------------------------------------------------------------------
-- OBJECTIVE: Create Tasks to Orchestrate Stream Processing
-- WAREHOUSE: TRANSFORM_WH (Assumed to exist)
-------------------------------------------------------------------------------

USE DATABASE BRONZE_DB;
USE SCHEMA CONTROL;

-- 1. CRM Tasks
CREATE OR REPLACE TASK TSK_PROCESS_CUSTOMERS
    WAREHOUSE = TRANSFORM_WH
    SCHEDULE = '5 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('BRONZE_DB.BRONZE_CRM.STM_CUSTOMERS')
AS
    CALL BRONZE_DB.CONTROL.SP_PROCESS_BRONZE_STREAM(
        'BRONZE_DB.BRONZE_CRM.STM_CUSTOMERS',
        'SILVER_DB.CRM.CUSTOMERS',
        'CUSTOMER_ID'
    );

CREATE OR REPLACE TASK TSK_PROCESS_REGISTRATION_SOURCE
    WAREHOUSE = TRANSFORM_WH
    SCHEDULE = '5 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('BRONZE_DB.BRONZE_CRM.STM_CUSTOMER_REGISTRATION_SOURCE')
AS
    CALL BRONZE_DB.CONTROL.SP_PROCESS_BRONZE_STREAM(
        'BRONZE_DB.BRONZE_CRM.STM_CUSTOMER_REGISTRATION_SOURCE',
        'SILVER_DB.CRM.CUSTOMER_REGISTRATION_SOURCE',
        'REGISTRATION_SOURCE_ID'
    );

CREATE OR REPLACE TASK TSK_PROCESS_INCIDENTS
    WAREHOUSE = TRANSFORM_WH
    SCHEDULE = '5 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('BRONZE_DB.BRONZE_CRM.STM_INCIDENTS')
AS
    CALL BRONZE_DB.CONTROL.SP_PROCESS_BRONZE_STREAM(
        'BRONZE_DB.BRONZE_CRM.STM_INCIDENTS',
        'SILVER_DB.CRM.INCIDENTS',
        'INCIDENT_ID'
    );

CREATE OR REPLACE TASK TSK_PROCESS_INTERACTIONS
    WAREHOUSE = TRANSFORM_WH
    SCHEDULE = '5 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('BRONZE_DB.BRONZE_CRM.STM_INTERACTIONS')
AS
    CALL BRONZE_DB.CONTROL.SP_PROCESS_BRONZE_STREAM(
        'BRONZE_DB.BRONZE_CRM.STM_INTERACTIONS',
        'SILVER_DB.CRM.INTERACTIONS',
        'INTERACTION_ID'
    );

CREATE OR REPLACE TASK TSK_PROCESS_SURVEYS
    WAREHOUSE = TRANSFORM_WH
    SCHEDULE = '5 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('BRONZE_DB.BRONZE_CRM.STM_SURVEYS')
AS
    CALL BRONZE_DB.CONTROL.SP_PROCESS_BRONZE_STREAM(
        'BRONZE_DB.BRONZE_CRM.STM_SURVEYS',
        'SILVER_DB.CRM.SURVEYS',
        'SURVEY_ID'
    );

-- 2. ERP Tasks
CREATE OR REPLACE TASK TSK_PROCESS_ORDERS
    WAREHOUSE = TRANSFORM_WH
    SCHEDULE = '15 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('BRONZE_DB.BRONZE_ERP.STM_OE_ORDER_HEADERS_ALL')
AS
    CALL BRONZE_DB.CONTROL.SP_PROCESS_BRONZE_STREAM(
        'BRONZE_DB.BRONZE_ERP.STM_OE_ORDER_HEADERS_ALL',
        'SILVER_DB.ERP.OE_ORDER_HEADERS_ALL',
        'ORDER_ID'
    );

CREATE OR REPLACE TASK TSK_PROCESS_ORDER_LINES
    WAREHOUSE = TRANSFORM_WH
    SCHEDULE = '15 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('BRONZE_DB.BRONZE_ERP.STM_OE_ORDER_LINES_ALL')
AS
    CALL BRONZE_DB.CONTROL.SP_PROCESS_BRONZE_STREAM(
        'BRONZE_DB.BRONZE_ERP.STM_OE_ORDER_LINES_ALL',
        'SILVER_DB.ERP.OE_ORDER_LINES_ALL',
        'LINE_ID'
    );

CREATE OR REPLACE TASK TSK_PROCESS_ADDRESSES
    WAREHOUSE = TRANSFORM_WH
    SCHEDULE = '15 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('BRONZE_DB.BRONZE_ERP.STM_ADDRESSES')
AS
    CALL BRONZE_DB.CONTROL.SP_PROCESS_BRONZE_STREAM(
        'BRONZE_DB.BRONZE_ERP.STM_ADDRESSES',
        'SILVER_DB.ERP.ADDRESSES',
        'ADDRESS_ID'
    );

CREATE OR REPLACE TASK TSK_PROCESS_CITY_TIER
    WAREHOUSE = TRANSFORM_WH
    SCHEDULE = '60 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('BRONZE_DB.BRONZE_ERP.STM_CITY_TIER_MASTER')
AS
    CALL BRONZE_DB.CONTROL.SP_PROCESS_BRONZE_STREAM(
        'BRONZE_DB.BRONZE_ERP.STM_CITY_TIER_MASTER',
        'SILVER_DB.ERP.CITY_TIER_MASTER',
        'CITY,STATE'
    );

CREATE OR REPLACE TASK TSK_PROCESS_ITEMS
    WAREHOUSE = TRANSFORM_WH
    SCHEDULE = '60 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('BRONZE_DB.BRONZE_ERP.STM_MTL_SYSTEM_ITEMS_B')
AS
    CALL BRONZE_DB.CONTROL.SP_PROCESS_BRONZE_STREAM(
        'BRONZE_DB.BRONZE_ERP.STM_MTL_SYSTEM_ITEMS_B',
        'SILVER_DB.ERP.MTL_SYSTEM_ITEMS_B',
        'INVENTORY_ITEM_ID'
    );

CREATE OR REPLACE TASK TSK_PROCESS_CATEGORIES
    WAREHOUSE = TRANSFORM_WH
    SCHEDULE = '60 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('BRONZE_DB.BRONZE_ERP.STM_CATEGORIES')
AS
    CALL BRONZE_DB.CONTROL.SP_PROCESS_BRONZE_STREAM(
        'BRONZE_DB.BRONZE_ERP.STM_CATEGORIES',
        'SILVER_DB.ERP.CATEGORIES',
        'CATEGORY_ID'
    );

CREATE OR REPLACE TASK TSK_PROCESS_BRANDS
    WAREHOUSE = TRANSFORM_WH
    SCHEDULE = '60 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('BRONZE_DB.BRONZE_ERP.STM_BRANDS')
AS
    CALL BRONZE_DB.CONTROL.SP_PROCESS_BRONZE_STREAM(
        'BRONZE_DB.BRONZE_ERP.STM_BRANDS',
        'SILVER_DB.ERP.BRANDS',
        'BRAND_ID'
    );

-- 3. Marketing Tasks
CREATE OR REPLACE TASK TSK_PROCESS_CAMPAIGNS
    WAREHOUSE = TRANSFORM_WH
    SCHEDULE = '360 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('BRONZE_DB.BRONZE_MARKETING.STM_MARKETING_CAMPAIGNS')
AS
    CALL BRONZE_DB.CONTROL.SP_PROCESS_BRONZE_STREAM(
        'BRONZE_DB.BRONZE_MARKETING.STM_MARKETING_CAMPAIGNS',
        'SILVER_DB.MARKETING.MARKETING_CAMPAIGNS',
        'CAMPAIGN_ID'
    );

-- 4. Resume All Tasks
ALTER TASK TSK_PROCESS_CUSTOMERS RESUME;
ALTER TASK TSK_PROCESS_REGISTRATION_SOURCE RESUME;
ALTER TASK TSK_PROCESS_INCIDENTS RESUME;
ALTER TASK TSK_PROCESS_INTERACTIONS RESUME;
ALTER TASK TSK_PROCESS_SURVEYS RESUME;
ALTER TASK TSK_PROCESS_ORDERS RESUME;
ALTER TASK TSK_PROCESS_ORDER_LINES RESUME;
ALTER TASK TSK_PROCESS_ADDRESSES RESUME;
ALTER TASK TSK_PROCESS_CITY_TIER RESUME;
ALTER TASK TSK_PROCESS_ITEMS RESUME;
ALTER TASK TSK_PROCESS_CATEGORIES RESUME;
ALTER TASK TSK_PROCESS_BRANDS RESUME;
ALTER TASK TSK_PROCESS_CAMPAIGNS RESUME;