-------------------------------------------------------------------------------
-- OBJECTIVE: Create Control Tables for Pipeline Orchestration
-- SCHEMA: BRONZE_DB.CONTROL
-------------------------------------------------------------------------------

USE DATABASE BRONZE_DB;
USE SCHEMA CONTROL;

-- 1. Source Systems Registry
CREATE OR REPLACE TABLE SOURCE_SYSTEMS (
    SOURCE_SYSTEM_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    SOURCE_SYSTEM_NAME VARCHAR(100) NOT NULL,
    SOURCE_SYSTEM_TYPE VARCHAR(50),
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 2. Table Metadata (Critical for Dynamic Processing)
CREATE OR REPLACE TABLE TABLE_METADATA (
    TABLE_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    SOURCE_SYSTEM_ID NUMBER REFERENCES SOURCE_SYSTEMS(SOURCE_SYSTEM_ID),
    SCHEMA_NAME VARCHAR(100) NOT NULL,
    TABLE_NAME VARCHAR(100) NOT NULL,
    PRIMARY_KEY_COLUMNS VARCHAR(500), -- Comma separated for composite keys
    LOAD_TYPE VARCHAR(20), -- 'FULL' or 'INCREMENTAL'
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    INITIAL_LOAD_COMPLETED BOOLEAN DEFAULT FALSE,
    LAST_SYNC_TIMESTAMP TIMESTAMP_NTZ,
    LAST_LOAD_STATUS VARCHAR(50),
    RECORDS_LOADED NUMBER DEFAULT 0,
    BRONZE_TABLE_NAME VARCHAR(200),
    SILVER_TABLE_NAME VARCHAR(200),
    LOAD_PRIORITY NUMBER DEFAULT 100,
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    MODIFIED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 3. Fivetran Connector Registry
CREATE OR REPLACE TABLE FIVETRAN_CONNECTORS (
    CONNECTOR_ID VARCHAR(100) PRIMARY KEY,
    CONNECTOR_NAME VARCHAR(200),
    SOURCE_SYSTEM_ID NUMBER REFERENCES SOURCE_SYSTEMS(SOURCE_SYSTEM_ID),
    CONNECTOR_TYPE VARCHAR(100),
    SYNC_FREQUENCY VARCHAR(50),
    IS_PAUSED BOOLEAN DEFAULT FALSE,
    LAST_SYNC_TIME TIMESTAMP_NTZ
);

-- 4. Stream Metadata
CREATE OR REPLACE TABLE STREAM_METADATA (
    STREAM_NAME VARCHAR(200) PRIMARY KEY,
    SOURCE_TABLE VARCHAR(200),
    TARGET_TABLE VARCHAR(200),
    STREAM_TYPE VARCHAR(50) DEFAULT 'STANDARD',
    IS_ACTIVE BOOLEAN DEFAULT TRUE
);

-- 5. Task Execution Log
CREATE OR REPLACE TABLE TASK_EXECUTION_LOG (
    LOG_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    TASK_NAME VARCHAR(200),
    EXECUTION_STATUS VARCHAR(50),
    RECORDS_PROCESSED NUMBER,
    START_TIME TIMESTAMP_NTZ,
    END_TIME TIMESTAMP_NTZ,
    ERROR_MESSAGE VARCHAR(5000)
);