-------------------------------------------------------------------------------
-- OBJECTIVE: Populate Control Tables based on LLD Specifications
-------------------------------------------------------------------------------

USE DATABASE BRONZE_DB;
USE SCHEMA CONTROL;

-- 1. Populate Source Systems
INSERT INTO SOURCE_SYSTEMS (SOURCE_SYSTEM_NAME, SOURCE_SYSTEM_TYPE) VALUES 
('SRC-001: ERP', 'AZURE_SQL'),
('SRC-002: CRM', 'AZURE_SQL'),
('SRC-003: MARKETING', 'AZURE_SQL');

-- 2. Populate Table Metadata
-- Note: IDs 1=ERP, 2=CRM, 3=MARKETING based on insertion order above

-- CRM Tables (Source ID 2)
INSERT INTO TABLE_METADATA (SOURCE_SYSTEM_ID, SCHEMA_NAME, TABLE_NAME, PRIMARY_KEY_COLUMNS, LOAD_TYPE, BRONZE_TABLE_NAME, SILVER_TABLE_NAME) VALUES
(2, 'BRONZE_CRM', 'CUSTOMERS', 'CUSTOMER_ID', 'INCREMENTAL', 'BRONZE_DB.BRONZE_CRM.CUSTOMERS', 'SILVER_DB.CRM.CUSTOMERS'),
(2, 'BRONZE_CRM', 'CUSTOMER_REGISTRATION_SOURCE', 'REGISTRATION_SOURCE_ID', 'INCREMENTAL', 'BRONZE_DB.BRONZE_CRM.CUSTOMER_REGISTRATION_SOURCE', 'SILVER_DB.CRM.CUSTOMER_REGISTRATION_SOURCE'),
(2, 'BRONZE_CRM', 'INCIDENTS', 'INCIDENT_ID', 'INCREMENTAL', 'BRONZE_DB.BRONZE_CRM.INCIDENTS', 'SILVER_DB.CRM.INCIDENTS'),
(2, 'BRONZE_CRM', 'INTERACTIONS', 'INTERACTION_ID', 'INCREMENTAL', 'BRONZE_DB.BRONZE_CRM.INTERACTIONS', 'SILVER_DB.CRM.INTERACTIONS'),
(2, 'BRONZE_CRM', 'SURVEYS', 'SURVEY_ID', 'INCREMENTAL', 'BRONZE_DB.BRONZE_CRM.SURVEYS', 'SILVER_DB.CRM.SURVEYS');

-- ERP Tables (Source ID 1)
INSERT INTO TABLE_METADATA (SOURCE_SYSTEM_ID, SCHEMA_NAME, TABLE_NAME, PRIMARY_KEY_COLUMNS, LOAD_TYPE, BRONZE_TABLE_NAME, SILVER_TABLE_NAME) VALUES
(1, 'BRONZE_ERP', 'OE_ORDER_HEADERS_ALL', 'ORDER_ID', 'INCREMENTAL', 'BRONZE_DB.BRONZE_ERP.OE_ORDER_HEADERS_ALL', 'SILVER_DB.ERP.OE_ORDER_HEADERS_ALL'),
(1, 'BRONZE_ERP', 'OE_ORDER_LINES_ALL', 'LINE_ID', 'INCREMENTAL', 'BRONZE_DB.BRONZE_ERP.OE_ORDER_LINES_ALL', 'SILVER_DB.ERP.OE_ORDER_LINES_ALL'),
(1, 'BRONZE_ERP', 'ADDRESSES', 'ADDRESS_ID', 'INCREMENTAL', 'BRONZE_DB.BRONZE_ERP.ADDRESSES', 'SILVER_DB.ERP.ADDRESSES'),
(1, 'BRONZE_ERP', 'CITY_TIER_MASTER', 'CITY,STATE', 'FULL', 'BRONZE_DB.BRONZE_ERP.CITY_TIER_MASTER', 'SILVER_DB.ERP.CITY_TIER_MASTER'),
(1, 'BRONZE_ERP', 'MTL_SYSTEM_ITEMS_B', 'INVENTORY_ITEM_ID', 'INCREMENTAL', 'BRONZE_DB.BRONZE_ERP.MTL_SYSTEM_ITEMS_B', 'SILVER_DB.ERP.MTL_SYSTEM_ITEMS_B'),
(1, 'BRONZE_ERP', 'CATEGORIES', 'CATEGORY_ID', 'INCREMENTAL', 'BRONZE_DB.BRONZE_ERP.CATEGORIES', 'SILVER_DB.ERP.CATEGORIES'),
(1, 'BRONZE_ERP', 'BRANDS', 'BRAND_ID', 'INCREMENTAL', 'BRONZE_DB.BRONZE_ERP.BRANDS', 'SILVER_DB.ERP.BRANDS');

-- Marketing Tables (Source ID 3)
INSERT INTO TABLE_METADATA (SOURCE_SYSTEM_ID, SCHEMA_NAME, TABLE_NAME, PRIMARY_KEY_COLUMNS, LOAD_TYPE, BRONZE_TABLE_NAME, SILVER_TABLE_NAME) VALUES
(3, 'BRONZE_MARKETING', 'MARKETING_CAMPAIGNS', 'CAMPAIGN_ID', 'INCREMENTAL', 'BRONZE_DB.BRONZE_MARKETING.MARKETING_CAMPAIGNS', 'SILVER_DB.MARKETING.MARKETING_CAMPAIGNS');

-- 3. Populate Stream Metadata
INSERT INTO STREAM_METADATA (STREAM_NAME, SOURCE_TABLE, TARGET_TABLE) 
SELECT 
    SCHEMA_NAME || '.STM_' || TABLE_NAME, 
    BRONZE_TABLE_NAME, 
    SILVER_TABLE_NAME
FROM TABLE_METADATA;