-------------------------------------------------------------------------------
-- OBJECTIVE: Apply PII Masking Policies
-- ROLE: SECURITYADMIN or ACCOUNTADMIN
-------------------------------------------------------------------------------

USE ROLE SECURITYADMIN;

-- 1. Create Masking Policy
CREATE OR REPLACE MASKING POLICY MASK_PII_STRING AS (VAL STRING) RETURNS STRING ->
    CASE
        WHEN CURRENT_ROLE() IN ('COMPLIANCE_OFFICER', 'ACCOUNTADMIN') THEN VAL
        ELSE '***MASKED***'
    END;

-- 2. Apply to CRM Customers
ALTER TABLE BRONZE_DB.BRONZE_CRM.CUSTOMERS 
MODIFY COLUMN EMAIL SET MASKING POLICY MASK_PII_STRING;

ALTER TABLE BRONZE_DB.BRONZE_CRM.CUSTOMERS 
MODIFY COLUMN PHONE SET MASKING POLICY MASK_PII_STRING;

-- 3. Apply to ERP Addresses
ALTER TABLE BRONZE_DB.BRONZE_ERP.ADDRESSES 
MODIFY COLUMN PHONE SET MASKING POLICY MASK_PII_STRING;

-- 4. Grant Usage to Roles
GRANT USAGE ON DATABASE BRONZE_DB TO ROLE TRANSFORMER_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE BRONZE_DB TO ROLE TRANSFORMER_ROLE;
GRANT SELECT ON ALL TABLES IN DATABASE BRONZE_DB TO ROLE TRANSFORMER_ROLE;
GRANT SELECT ON ALL STREAMS IN DATABASE BRONZE_DB TO ROLE TRANSFORMER_ROLE;