CREATE OR REPLACE PROCEDURE BRONZE_DB.CONTROL.SP_GET_TABLE_LOAD_ORDER()
RETURNS TABLE (
    TABLE_NAME VARCHAR,
    SCHEMA_NAME VARCHAR,
    LOAD_PRIORITY NUMBER
)
LANGUAGE SQL
AS
$$
DECLARE
    res RESULTSET;
BEGIN
    -- Simple priority based fetch, can be expanded to recursive CTE if dependencies exist
    res := (
        SELECT TABLE_NAME, SCHEMA_NAME, LOAD_PRIORITY
        FROM BRONZE_DB.CONTROL.TABLE_METADATA
        WHERE IS_ACTIVE = TRUE
        ORDER BY LOAD_PRIORITY ASC
    );
    RETURN TABLE(res);
END;
$$;