CREATE OR REPLACE PROCEDURE BRONZE_DB.CONTROL.SP_UPDATE_TABLE_METADATA(
    P_TABLE_NAME VARCHAR,
    P_STATUS VARCHAR,
    P_RECORDS_LOADED NUMBER,
    P_MARK_INITIAL_COMPLETE BOOLEAN
)
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
BEGIN
    -- Update the metadata table
    UPDATE BRONZE_DB.CONTROL.TABLE_METADATA
    SET 
        LAST_LOAD_STATUS = :P_STATUS,
        RECORDS_LOADED = :P_RECORDS_LOADED,
        LAST_SYNC_TIMESTAMP = CURRENT_TIMESTAMP(),
        MODIFIED_DATE = CURRENT_TIMESTAMP(),
        INITIAL_LOAD_COMPLETED = CASE 
                                    WHEN :P_MARK_INITIAL_COMPLETE = TRUE AND :P_STATUS = 'SUCCESS' 
                                    THEN TRUE 
                                    ELSE INITIAL_LOAD_COMPLETED 
                                 END
    WHERE TABLE_NAME = :P_TABLE_NAME;

    RETURN 'Metadata updated for ' || P_TABLE_NAME;
END;
$$;