-------------------------------------------------------------------------------
-- OBJECTIVE: Create Snowflake Streams for CDC
-- NOTE: Tables must exist (loaded by Fivetran) before running this.
-------------------------------------------------------------------------------

USE DATABASE BRONZE_DB;

-- CRM Streams
CREATE STREAM IF NOT EXISTS BRONZE_CRM.STM_CUSTOMERS 
    ON TABLE BRONZE_CRM.CUSTOMERS 
    APPEND_ONLY = FALSE 
    SHOW_INITIAL_ROWS = TRUE;

CREATE STREAM IF NOT EXISTS BRONZE_CRM.STM_CUSTOMER_REGISTRATION_SOURCE 
    ON TABLE BRONZE_CRM.CUSTOMER_REGISTRATION_SOURCE 
    APPEND_ONLY = FALSE 
    SHOW_INITIAL_ROWS = TRUE;

CREATE STREAM IF NOT EXISTS BRONZE_CRM.STM_INCIDENTS 
    ON TABLE BRONZE_CRM.INCIDENTS 
    APPEND_ONLY = FALSE 
    SHOW_INITIAL_ROWS = TRUE;

CREATE STREAM IF NOT EXISTS BRONZE_CRM.STM_INTERACTIONS 
    ON TABLE BRONZE_CRM.INTERACTIONS 
    APPEND_ONLY = FALSE 
    SHOW_INITIAL_ROWS = TRUE;

CREATE STREAM IF NOT EXISTS BRONZE_CRM.STM_SURVEYS 
    ON TABLE BRONZE_CRM.SURVEYS 
    APPEND_ONLY = FALSE 
    SHOW_INITIAL_ROWS = TRUE;

-- ERP Streams
CREATE STREAM IF NOT EXISTS BRONZE_ERP.STM_OE_ORDER_HEADERS_ALL 
    ON TABLE BRONZE_ERP.OE_ORDER_HEADERS_ALL 
    APPEND_ONLY = FALSE 
    SHOW_INITIAL_ROWS = TRUE;

CREATE STREAM IF NOT EXISTS BRONZE_ERP.STM_OE_ORDER_LINES_ALL 
    ON TABLE BRONZE_ERP.OE_ORDER_LINES_ALL 
    APPEND_ONLY = FALSE 
    SHOW_INITIAL_ROWS = TRUE;

CREATE STREAM IF NOT EXISTS BRONZE_ERP.STM_ADDRESSES 
    ON TABLE BRONZE_ERP.ADDRESSES 
    APPEND_ONLY = FALSE 
    SHOW_INITIAL_ROWS = TRUE;

CREATE STREAM IF NOT EXISTS BRONZE_ERP.STM_CITY_TIER_MASTER 
    ON TABLE BRONZE_ERP.CITY_TIER_MASTER 
    APPEND_ONLY = FALSE 
    SHOW_INITIAL_ROWS = TRUE;

CREATE STREAM IF NOT EXISTS BRONZE_ERP.STM_MTL_SYSTEM_ITEMS_B 
    ON TABLE BRONZE_ERP.MTL_SYSTEM_ITEMS_B 
    APPEND_ONLY = FALSE 
    SHOW_INITIAL_ROWS = TRUE;

CREATE STREAM IF NOT EXISTS BRONZE_ERP.STM_CATEGORIES 
    ON TABLE BRONZE_ERP.CATEGORIES 
    APPEND_ONLY = FALSE 
    SHOW_INITIAL_ROWS = TRUE;

CREATE STREAM IF NOT EXISTS BRONZE_ERP.STM_BRANDS 
    ON TABLE BRONZE_ERP.BRANDS 
    APPEND_ONLY = FALSE 
    SHOW_INITIAL_ROWS = TRUE;

-- Marketing Streams
CREATE STREAM IF NOT EXISTS BRONZE_MARKETING.STM_MARKETING_CAMPAIGNS 
    ON TABLE BRONZE_MARKETING.MARKETING_CAMPAIGNS 
    APPEND_ONLY = FALSE 
    SHOW_INITIAL_ROWS = TRUE;